export const HISTORY_UNDO = 'HISTORY_UNDO';
export const HISTORY_REDO = 'HISTORY_REDO';
export const HISTORY_ADD = 'HISTORY_ADD';
export const HISTORY_TO = 'HISTORY_TO';
export const HISTORY_REPLACE = 'HISTORY_REPLACE';
export const LOAD_NEW_COMPONENT = 'LOAD_NEW_COMPONENT';
export const TEST = 'TEST';
export const CREATE_PAGE = 'CREATE_PAGE';
export const DELETE_PAGE = 'DELETE_PAGE';
export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_PAGE_STYLE = 'UPDATE_PAGE_STYLE';

export const CREATE_ELEMENT = 'CREATE_ELEMENT';
export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';
export const UPDATE_ELEMENT_VIEW_CONFIG = 'UPDATE_ELEMENT_VIEW_CONFIG';
export const UPDATE_ELEMENT_ATTR = 'UPDATE_ELEMENT_ATTR';
export const UPDATE_ELEMENT_DATA = 'UPDATE_ELEMENT_DATA';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const CLEAR_SELECTED_ELEMENTS = 'CLEAR_SELECTED_ELEMENTS';
export const ADD_SELECTED_ELEMENT = 'ADD_SELECTED_ELEMENT';
export const ADD_SELECTED_ELEMENTS = 'ADD_SELECTED_ELEMENTS';
export const REMOVE_SELECTED_ELEMENT = 'REMOVE_SELECTED_ELEMENT';
export const TOGGLE_SELECT_STATUS = 'TOGGLE_SELECT_STATUS';
export const LOAD_PROJECT_INFO = 'LOAD_PROJECT_INFO';
export const TOGGLE_BLOCK_LOADING_STATUS = 'TOGGLE_BLOCK_LOADING_STATUS';

export const DELETE_ITEMS = 'DELETE_ITEMS';
export const SET_ELEMENT_CONFIG_VALUE = 'SET_ELEMENT_CONFIG_VALUE';

export const UPDATE_ELEMENT_DATA_CONFIG = 'UPDATE_ELEMENT_DATA_CONFIG';

export const ALIGNMENT_ITEMS = 'ALIGNMENT_ITEMS';
export const DISTRIBUTE_ITEMS = 'DISTRIBUTE_ITEMS';
export const LOAD_DATA_SOURCE = 'LOAD_DATA_SOURCE';
export const SELECT_ELEMENTS = 'SELECT_ELEMENTS';
export const UPDATE_ELEMENTS_ATTR = 'UPDATE_ELEMENTS_ATTR';

export const MAKE_GROUP = 'MAKE_GROUP';
export const UN_GROUP = 'UN_GROUP';
export const CALC_GROUP_ATTR = 'CALC_GROUP_ATTR';
export const CLEAR_SELECTED_ITEM_IDS = 'CLEAR_SELECTED_ITEM_IDS';

export const ADD_DATA_SOURCE = 'ADD_DATA_SOURCE';
export const DELETE_DATA_SOURCE = 'DELETE_DATA_SOURCE';
export const UPDATE_DATA_SOURCE_CONFIG = 'UPDATE_DATA_SOURCE_CONFIG';
export const SET_INTERVAL_ID = 'SET_INTERVAL_ID';
export const UPDATE_DATA_SOURCE_VALUE = 'UPDATE_DATA_SOURCE_VALUE';

export const LOAD_DATA_FILTER = 'LOAD_DATA_FILTER';
export const ADD_DATA_FILTER = 'ADD_DATA_FILTER';
export const DELETE_DATA_FILTER = 'DELETE_DATA_FILTER';
export const UPDATE_DATA_FILTER_CONFIG = 'UPDATE_DATA_FILTER_CONFIG';
export const UPDATE_DATA_FILTER_VALUE = 'UPDATE_DATA_FILTER_VALUE';
export const RESORT_Z_INDEX = 'RESORT_Z_INDEX';
export const SET_VIEW_PORT_SIZE = 'SET_VIEW_PORT_SIZE';
export const UPDATE_ONENET_DATA = 'UPDATE_ONENET_DATA';

export const CREATE_D_OBJECT = 'CREATE_D_OBJECT';
export const DELETE_D_OBJECTS = 'DELETE_D_OBJECTS';
export const CREATE_THREE_D_MODEL = 'CREATE_THREE_D_MODEL';
export const SET_MODEL_INFO = 'SET_MODEL_INFO';
export const SELECT_3D_MODEL = 'SELECT_3D_MODEL';
export const SET_ACTION_TYPE = 'SET_ACTION_TYPE';
export const LOAD_3D = 'LOAD_3D';
export const LOADED_PROJECT = 'LOADED_PROJECT';
export const MAIN_EDITOR_EVENT_BIND = 'MAIN_EDITOR_EVENT_BIND';
export const SET_URL_PARAMS = 'SET_URL_PARAMS';
export const UPDATE_API_DATA = 'UPDATE_API_DATA';
export const SET_EDITOR_SCALE = 'SET_EDITOR_SCALE';
export const SET_VIEW_SCALE = 'SET_VIEW_SCALE';
export const CALC_EDITOR_SCALE = 'CALC_EDITOR_SCALE';
export const CALC_VIEW_SCALE = 'CALC_VIEW_SCALE';
export const COPY_SELECTED_ITEMS = 'COPY_SELECTED_ITEMS';
export const PASTE_ELEMENTS = 'PASTE_ELEMENTS';
export const TOGGLE_WEBSOCKET = 'TOGGLE_WEBSOCKET';
export const ADD_DATA_SOURCE_PRE = 'ADD_DATA_SOURCE_PRE';
export const CHANGE_DATA_SOURCE_PRE = 'CHANGE_DATA_SOURCE_PRE';
export const CHANGE_CURRENT_ITEM = 'CHANGE_CURRENT_ITEM';
